#!/bin/bash
# SYNCWISE PRODUCTION FIXES - QUICK ACTION CHECKLIST
# Date: April 9, 2026
# Status: ✅ CODE COMPLETE - Awaiting your database setup

echo "============================================"
echo "SYNCWISE PRODUCTION FIXES - CHECKLIST"
echo "============================================"
echo ""

# 1. Code verification
echo "[STEP 1] Verify code was created..."
echo ""

files_to_check=(
    "services/userProfileService.ts"
    "hooks/useUserProfile.ts"
    "app/auth/setup-profile/page.tsx"
    "docs/USER_PROFILES_MIGRATION.sql"
    "docs/PRODUCTION_FIXES_GUIDE.md"
    "docs/QUICK_SETUP.md"
)

for file in "${files_to_check[@]}"; do
    if [ -f "syncwise-ai/$file" ]; then
        echo "✅ $file"
    else
        echo "❌ $file (MISSING)"
    fi
done

echo ""
echo "============================================"
echo "[STEP 2] Database Setup (REQUIRED)"
echo "============================================"
echo ""
echo "INSTRUCTIONS:"
echo "1. Go to: https://app.supabase.com"
echo "2. Select your SyncWise project"
echo "3. Click: SQL Editor (left sidebar)"
echo ""
echo "4. Create first query:"
echo "   - Copy entire contents of: docs/USER_PROFILES_MIGRATION.sql"
echo "   - Paste in SQL Editor"
echo "   - Click 'Run' (green button)"
echo "   - Verify: user_profiles table created ✓"
echo ""
echo "5. Create second query (Task RLS):"
echo "   - Copy from: docs/QUICK_SETUP.md (lines for tasks RLS)"
echo "   - Run the SQL"
echo "   - Verify: tasks table RLS policies created ✓"
echo ""
echo "6. Disable email confirmation:"
echo "   - Click: Authentication (sidebar)"
echo "   - Click: Email Templates"
echo "   - Toggle OFF: 'Confirm email'"
echo ""

echo "============================================"
echo "[STEP 3] Local Testing"
echo "============================================"
echo ""
echo "Start dev server:"
echo "  npm run dev"
echo ""
echo "Test script:"
echo "  1. Go to http://localhost:3000/auth/login"
echo "  2. Click 'Sign Up'"
echo "  3. Enter email, password, name"
echo "  4. Should redirect to /auth/setup-profile"
echo "  5. Enter name + DOB (optional)"
echo "  6. Click 'Complete Profile'"
echo "  7. Should redirect to /dashboard/tasks"
echo "  8. Check sidebar → shows your name ✓"
echo "  9. Create task → verify appears in list ✓"
echo "  10. Open incognito window, signup as different user"
echo "  11. Verify they DON'T see first user's tasks ✓"
echo ""

echo "============================================"
echo "[STEP 4] Verify Logs"
echo "============================================"
echo ""
echo "Open browser console (F12 → Console tab)"
echo "Look for logs when taking actions:"
echo ""
echo "On signup:"
echo "  ✅ [AuthProvider] Auth state changed: [user-id]"
echo ""
echo "On setup-profile:"
echo "  ✅ [SetupProfilePage] Profile created, redirecting"
echo ""
echo "On dashboard:"
echo "  ✅ [fetchTasks] Retrieved X tasks"
echo ""
echo "On create task:"
echo "  ✅ [createTask] Task created successfully"
echo "  ✅ [addTask] UI refreshed - tasks reloaded"
echo ""

echo "============================================"
echo "[STEP 5] Troubleshooting"
echo "============================================"
echo ""
echo "Problem: Task doesn't appear"
echo "  - Check Network tab: POST /tasks → verify user_id in body"
echo "  - Supabase SQL: SELECT * FROM tasks WHERE user_id = '[YOUR_ID]';"
echo "  - Console: Look for ❌ errors"
echo ""
echo "Problem: Stuck on setup-profile"
echo "  - Console: Check for profile creation errors"
echo "  - Supabase: User_profiles table has your record?"
echo "  - Try: Manual redirect to /dashboard/tasks"
echo ""
echo "Problem: 'New row violates row-level security'"
echo "  - Did you run task RLS SQL? (Step 2, second query)"
echo "  - Check user_id is in insert payload"
echo "  - Verify RLS policies exist in Supabase"
echo ""

echo "============================================"
echo "DOCUMENTATION"
echo "============================================"
echo ""
echo "Read these files for details:"
echo "  1. docs/IMPLEMENTATION_COMPLETE.md - What was done"
echo "  2. docs/QUICK_SETUP.md - 5-minute reference"
echo "  3. docs/PRODUCTION_FIXES_GUIDE.md - Full guide"
echo "  4. docs/CHANGES_DETAILED.md - Code changes explained"
echo ""

echo "============================================"
echo "✅ ALL CODE CHANGES COMPLETE!"
echo "============================================"
echo ""
echo "Next step: Run database setup (Step 2)"
echo ""
